<a href="https://colab.research.google.com/github/durbin-164/TensorFlow-Basic-Work/blob/master/Basic_TensorFlow_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Read carefully: 

https://www.tensorflow.org/guide/tensors

https://www.tensorflow.org/versions/r2.0/api_docs/python

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.0.0-beta1


In [0]:
!pip install tensorflow==2.0.0-beta1

In [0]:
#tf.enable_eager_execution()
#tf.compat.v1.disable_eager_execution()

tf.executing_eagerly()

True

Variables are created by auto type casting or define type casting


In [2]:
a = tf.Variable(10)
b = tf.Variable(20, dtype=tf.float64)
c = tf.Variable([1,2,3,4,5,6], shape = [3,2])
d = tf.Variable('Rasel', dtype=tf.string)

a.assign(a-20)
a.assign_add(30)

print(a)
print(b)
print(c)
print(d)
print(c[1])
print(c.shape)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>
<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=20.0>
<tf.Variable 'Variable:0' shape=[3, 2] dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Rasel'>
tf.Tensor(2, shape=(), dtype=int32)
[3, 2]


In [0]:
aa = tf.constant(1)
bb = tf.constant([1,2,3])
cc = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(aa)
print(bb)
print(cc)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [0]:
zero = tf.zeros([3,3])
print(zero)


tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [0]:
one = tf.ones([3,3,2])
print(one)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 3, 2), dtype=float32)


In [0]:
print(tf.rank(one))
print(tf.shape(one))
print(one.shape)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 3 2], shape=(3,), dtype=int32)
(3, 3, 2)


In [0]:
matx = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
print(matx)


<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [0]:
print(matx[:,1])
print(matx[1,:])

tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [0]:
matx2 = tf.ones([4,5,6])
matx21 = tf.reshape(matx2,[4,30])
matx22 = tf.reshape(matx2,[4,-1]) # -1 tells reshape to calculate the size of this dimension.

print(matx2.shape)
print(matx21.shape)
print(matx22.shape)

(4, 5, 6)
(4, 30)
(4, 30)


It is possible to cast tf.Tensors from one datatype to another using tf.cast

In [0]:
float_data = tf.cast(tf.constant([1,2,3]), dtype = tf.float32)
print(float_data)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [0]:
const = tf.constant([1,2,3])
mul = const*const

print(mul)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


Different math operation

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math

In [0]:
a = tf.constant([1,-10,30,-40])
b = tf.constant([2, 20, -30,50])
print(tf.abs(a))
print(tf.add(a,b)) #Returns x + y element-wise.
print(tf.add_n([a,b,a])) # Adds all input tensors element-wise.
print(tf.argmax(a)) #Returns the index with the largest value across axes of a tensor.
print(tf.argmin(a)) #Returns the index with the smallest value across axes of a tensor.
print(tf.divide(a,b)) #Computes Python style division of x by y.
#print(tf.divide_no_nan(a,b))#Computes an unsafe divide which returns 0 if the y is zero.

print(tf.maximum(a,b)) #Returns the max of x and y (i.e. x > y ? x : y) element-wise.
print(tf.multiply(a,b)) # Returns x * y element-wise.

print(tf.reduce_max(a)) # Computes the maximum of elements across dimensions of a tensor.
print(tf.reduce_max([a,b])) # Computes the maximum of elements across dimensions of a tensor.
print(tf.reduce_min(a)) # Computes the minimum of elements across dimensions of a tensor.
print(tf.reduce_mean(a)) # Computes the mean of elements across dimensions of a tensor.
print(tf.reduce_sum(a)) 
print(tf.reduce_prod(a))
print(tf.math.reduce_std(tf.constant([1,4,6,16], dtype=tf.float32))) #dtype must be float


print(tf.pow(a,3))
print(tf.sqrt(tf.constant([1,4,6,16], dtype=tf.float32))) # dtype = tf.int32 will not work.

x = tf.matmul([[1]], [[2, 3]])
print(x)

x = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
y = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(tf.matmul(x, y))

x = tf.constant([[1,2],[3,4]])
y = tf.constant([[6,7],[8,9]])
print(x.shape)
print(y.shape)
print(tf.matmul(x,y))






tf.Tensor([ 1 10 30 40], shape=(4,), dtype=int32)
tf.Tensor([ 3 10  0 10], shape=(4,), dtype=int32)
tf.Tensor([  4   0  30 -30], shape=(4,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([ 0.5 -0.5 -1.  -0.8], shape=(4,), dtype=float64)
tf.Tensor([ 2 20 30 50], shape=(4,), dtype=int32)
tf.Tensor([    2  -200  -900 -2000], shape=(4,), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(-40, shape=(), dtype=int32)
tf.Tensor(-4, shape=(), dtype=int32)
tf.Tensor(-19, shape=(), dtype=int32)
tf.Tensor(12000, shape=(), dtype=int32)
tf.Tensor(5.629165, shape=(), dtype=float32)
tf.Tensor([     1  -1000  27000 -64000], shape=(4,), dtype=int32)
tf.Tensor([1.        2.        2.4494898 4.       ], shape=(4,), dtype=float32)
tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
(2, 2)
(2, 2)
tf.Tensor(
[[22 25]
 [50 57]], shape=(2, 2), dtype=int32)
